### ISSUE TITLE
Potential execution time improvement for compareSamples

### ISSUE THREAD

**Issue by pavlemarinkovic** [golharam/cohort-matcher#3]
Hi,

I have noticed that the runtime of the script can be improved for local execution. The subprocess library can run jobs in parallel. Moving the p.wait() out of the _run method, and later checking for errors could significantly improve execution time.

In **compareSamples.py**
```
def _run(cmd):
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    out, err = p.communicate()
    p.wait()
    if p.returncode != 0:
        return err
    return out
```

Though I believe this would require the TSV making step be moved out of the compareGenomes script, to avoid multiple instances of compareGenomes.py script trying to access and write to the same file.

**Comment by golharam** [comment]
Yes.  The serial local execution was meant to support easy debugging.  Any optimized running of this is workflow is done in AWS Batch.  I never considered optimizing for running locally.
